version: '3'

networks: 
    jeu-abeille.fr:
        driver: bridge

services: 
    backoffice:
        build: .
        volumes: 
            - ./back-office:/var/www/html
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
        working_dir: 
            /var/www/html
        ports: 
            - 8080:80
        networks: 
            - jeu-abeille.fr
        links: 
            - database
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=abeille
            - MYSQL_PASSWORD=abeille
            - MYSQL_DATABASE=abeille
        ports:
            - "3307:3306"
        networks:
            - jeu-abeille.fr
        volumes:
            - ./db-volume:/var/sql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        volumes:
            - /sessions
        ports:
            - 5000:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - database
        networks: 
            - jeu-abeille.fr